### ISSUE TITLE
[ISSUE]loggable isn't support gorm v2

### ISSUE THREAD

**Issue by xchwan** [sas1024/gorm-loggable#24]
I have use your loggable to create log for gorm v2 project, It shows 
```
cannot use db (variable of type *"gorm.io/gorm".DB) as *"github.com/jinzhu/gorm".DB value in argument to loggable.Register
```
Then, I checked the repo find it use github.com/jinzhu/gorm instead of gorm.io/gorm

**Comment by sas1024** [comment]
Yes, for now gorm-loggable is not maintainable and repo will be archived.
